# Generated by Django 3.1.3 on 2022-01-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat40', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProdServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveprodserv', models.TextField(blank=True, default='', null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('similar', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
