# Generated by Django 3.1.3 on 2022-10-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat40', '0003_auto_20220112_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formapago', models.TextField(blank=True, default='', null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodopago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodopago', models.TextField(blank=True, default='', null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
