version: '3'
services:
  dev:
# web
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
    - .:/hackernews
    ports:
    - "3000:8080"
#   - "8082:8080"
    env_file:
      - .env
