# Generated by Django 3.1.3 on 2022-01-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='diascredito',
            field=models.IntegerField(default=0),
        ),
    ]
