# Generated by Django 3.1.3 on 2022-01-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
        ('receptor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.lista'),
        ),
    ]
