# Generated by Django 3.1.3 on 2022-01-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_lista_tipo'),
        ('receptor', '0002_receptor_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptor',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listaprecio', to='precios.lista'),
        ),
    ]
