# Generated by Django 3.1.3 on 2022-01-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_auto_20220116_0606'),
        ('receptor', '0003_auto_20220116_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor',
            name='lista',
        ),
        migrations.AddField(
            model_name='receptor',
            name='listaprecio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='precios.lista'),
        ),
    ]
