# Generated by Django 3.1.3 on 2022-01-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='tipo',
            field=models.TextField(default=''),
        ),
    ]
