# Generated by Django 3.1.3 on 2022-01-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_auto_20220116_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios', related_query_name='precio', to='precios.lista'),
        ),
    ]
