# Generated by Django 3.1.3 on 2022-01-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0005_auto_20220116_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='tipolista',
            field=models.IntegerField(default=0),
        ),
    ]
