# Generated by Django 3.1.3 on 2021-07-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='claveunidad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='codigosat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='ieps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='noidentificacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='retiva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='trasladoiva',
            field=models.FloatField(default=0),
        ),
    ]
