# Generated by Django 3.1.3 on 2022-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210728_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='codigobarras',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='descripunidad',
            field=models.TextField(default='Pieza'),
        ),
        migrations.AddField(
            model_name='link',
            name='existencias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='stockmax',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='link',
            name='stockmin',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='claveunidad',
            field=models.TextField(default='H87'),
        ),
        migrations.AlterField(
            model_name='link',
            name='codigosat',
            field=models.TextField(default='01010101'),
        ),
    ]
