# Generated by Django 3.1.3 on 2022-01-13 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat40', '0003_auto_20220112_2018'),
        ('links', '0005_auto_20220112_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='ieps',
            new_name='retencionieps',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='retiva',
            new_name='retencionisr',
        ),
        migrations.RemoveField(
            model_name='link',
            name='descripunidad',
        ),
        migrations.AddField(
            model_name='link',
            name='retencioniva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='trasladoieps',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='claveunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigosat', to='cat40.claveunidad'),
        ),
        migrations.AlterField(
            model_name='link',
            name='codigosat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigosat', to='cat40.claveprodserv'),
        ),
    ]
