# Generated by Django 3.1.3 on 2022-01-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat40', '0003_auto_20220112_2018'),
        ('links', '0006_auto_20220113_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='claveunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat40.claveunidad'),
        ),
        migrations.AlterField(
            model_name='link',
            name='codigosat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat40.claveprodserv'),
        ),
    ]
