# Generated by Django 3.1.3 on 2021-07-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='certificado',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='emisor',
            name='regimenfiscal',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='filekey',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='passcertificado',
            field=models.TextField(default=''),
        ),
    ]
