# Generated by Django 3.1.3 on 2022-01-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('clave_transporte', models.TextField(blank=True)),
                ('nacionalidad', models.TextField(blank=True)),
                ('designador_iata', models.TextField(blank=True)),
                ('linea_ferrea', models.TextField(blank=True)),
            ],
        ),
    ]
