# Generated by Django 3.1.3 on 2022-01-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20220102_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='clave_transporte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='designador_iata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='linea_ferrea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nacionalidad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
