# Generated by Django 3.1.3 on 2022-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20220102_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.TextField(blank=True, null=True)),
                ('codigopostal', models.TextField(blank=True, null=True)),
                ('nombre_asentamiento', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
