# Generated by Django 3.1.3 on 2021-08-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210729_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='claveunidad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detail',
            name='codigosat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detail',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='ieps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='noidentificacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detail',
            name='retiva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='trasladoiva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
