# Generated by Django 3.1.3 on 2022-01-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='complneg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='complpago',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='pdf',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='statuscfdi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='statusv',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='xml',
            field=models.TextField(default=''),
        ),
    ]
