# Generated by Django 3.1.3 on 2022-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20220108_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='sales.Detail'),
        ),
    ]
