# Generated by Django 3.1.3 on 2022-01-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20220108_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='sales.sale'),
        ),
    ]
