# Generated by Django 3.1.3 on 2022-01-09 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20220109_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale'),
        ),
    ]
