# Generated by Django 3.1.3 on 2022-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20220112_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='ieps',
            new_name='retencionieps',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='retiva',
            new_name='retencionisr',
        ),
        migrations.AddField(
            model_name='detail',
            name='retencioniva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='trasladoieps',
            field=models.FloatField(default=0),
        ),
    ]
